// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using litWebApp.Models;

#nullable disable

namespace litWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310124429_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("ShipId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Vaha")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CargoTypes");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoTypeValueModel", b =>
                {
                    b.Property<int>("CargoTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CargoTypeId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("CargoTypeValues");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.HangarSpotModel", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.HasKey("StationId", "ShipId");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("HangarSpots");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.PlanetAffectingStationModel", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("integer");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.HasKey("PlanetId", "StationId");

                    b.HasIndex("StationId");

                    b.ToTable("PlanetAffectingStations");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.PlanetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoTypeId")
                        .HasColumnType("integer");

                    b.Property<float>("CoordinateX")
                        .HasColumnType("real");

                    b.Property<float>("CoordinateY")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.ShipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MnozstviPaliva")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.ShipTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoHold")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPaliva")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PathToTextures")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("ShipTypes");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.StationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CoordinateX")
                        .HasColumnType("real");

                    b.Property<float>("CoordinateY")
                        .HasColumnType("real");

                    b.Property<int>("HangarLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.CargoTypeModel", "CargoType")
                        .WithMany("Cargos")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("litWebApp.Models.DbModels.ShipModel", "Ship")
                        .WithMany("Cargos")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoTypeValueModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.CargoTypeModel", "CargoType")
                        .WithMany("CargoTypeValues")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("litWebApp.Models.DbModels.StationModel", "Station")
                        .WithMany("CargoTypeValues")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.HangarSpotModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.ShipModel", "Ship")
                        .WithOne("HangarSpot")
                        .HasForeignKey("litWebApp.Models.DbModels.HangarSpotModel", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("litWebApp.Models.DbModels.StationModel", "Station")
                        .WithMany("HangarSpots")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.PlanetAffectingStationModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.PlanetModel", "Planet")
                        .WithMany("PlanetAffectingStations")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("litWebApp.Models.DbModels.StationModel", "Station")
                        .WithMany("PlanetAffectingStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.PlanetModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.CargoTypeModel", "CargoType")
                        .WithMany("Planets")
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CargoType");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.ShipModel", b =>
                {
                    b.HasOne("litWebApp.Models.DbModels.ShipTypeModel", "ShipType")
                        .WithMany("Ships")
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("litWebApp.Models.DbModels.UserModel", "User")
                        .WithMany("Ships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.CargoTypeModel", b =>
                {
                    b.Navigation("CargoTypeValues");

                    b.Navigation("Cargos");

                    b.Navigation("Planets");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.PlanetModel", b =>
                {
                    b.Navigation("PlanetAffectingStations");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.ShipModel", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("HangarSpot");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.ShipTypeModel", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.StationModel", b =>
                {
                    b.Navigation("CargoTypeValues");

                    b.Navigation("HangarSpots");

                    b.Navigation("PlanetAffectingStations");
                });

            modelBuilder.Entity("litWebApp.Models.DbModels.UserModel", b =>
                {
                    b.Navigation("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
